### ISSUE TITLE
Network policies?

### ISSUE THREAD

**Issue by judepereira** [storyscript/stack-kubernetes#68]
- only engine (namespace Asyncy-system) can talk to other namespaces
- namespaces can't talk to each other
- within a namespace, everybody can talk to everybody

**Comment by joshpollara** [comment]
@judepereira i think we want the network policies below. i still have to figure out the best way to get them into [Kubernetes.py](https://github.com/storyscript/runtime/blob/master/storyruntime/Kubernetes.py).

```
# deny all from other namespaces except your own namespace
bender: ~/asyncy/tmp $  cat foo-deny-from-other-namespace.yaml
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: foo
  name: deny-from-other-namespaces
spec:
  podSelector:
    matchLabels:
  ingress:
  - from:
    - podSelector: {}
bender: ~/asyncy/tmp $  cat bar-deny-from-other-namespace.yaml
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: bar
  name: deny-from-other-namespaces
spec:
  podSelector:
    matchLabels:
  ingress:
  - from:
    - podSelector: {}
bender: ~/asyncy/tmp $

# allow all from asyncy-system
bender: ~/asyncy/tmp $  cat foo-allow-all-from-asyncy-system.yaml
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: foo
  name: foo-allow-all-from-asyncy-system
spec:
  podSelector: {}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: asyncy-system
bender: ~/asyncy/tmp $  cat bar-allow-all-from-asyncy-system.yaml
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: bar
  name: bar-allow-all-from-asyncy-system
spec:
  podSelector: {}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: asyncy-system
bender: ~/asyncy/tmp $
```
